using System.Net;
using CalloraVoipSdk.Core.Infrastructure.Stun.Client;

namespace CalloraVoipSdk.Core.IntegrationTests;

/// <summary>
/// Unit tests for <see cref="DnsSrvQuery.TryParseResolvConf"/>, the pure resolv.conf parser
/// backing system DNS resolver discovery. Filesystem-independent by design.
/// </summary>
public sealed class DnsSrvQueryResolvConfTests
{
    [Fact]
    public void TryParseResolvConf_ReturnsFirstValidNameserver_WhenMultiplePresent()
    {
        string[] lines =
        [
            "# generated by test",
            "search example.org",
            "nameserver 192.0.2.10",
            "nameserver 192.0.2.11",
        ];

        var found = DnsSrvQuery.TryParseResolvConf(lines, out var resolver);

        Assert.True(found);
        Assert.NotNull(resolver);
        Assert.Equal(IPAddress.Parse("192.0.2.10"), resolver!.Address);
        Assert.Equal(53, resolver.Port);
    }

    [Fact]
    public void TryParseResolvConf_SkipsInvalidEntries_AndReturnsFirstParsable()
    {
        string[] lines =
        [
            "nameserver not-an-ip",
            "nameserver 198.51.100.7",
        ];

        var found = DnsSrvQuery.TryParseResolvConf(lines, out var resolver);

        Assert.True(found);
        Assert.Equal(IPAddress.Parse("198.51.100.7"), resolver!.Address);
    }

    [Fact]
    public void TryParseResolvConf_ParsesIpv6Nameserver()
    {
        string[] lines = ["nameserver 2001:db8::1"];

        var found = DnsSrvQuery.TryParseResolvConf(lines, out var resolver);

        Assert.True(found);
        Assert.Equal(IPAddress.Parse("2001:db8::1"), resolver!.Address);
        Assert.Equal(53, resolver.Port);
    }

    [Fact]
    public void TryParseResolvConf_ReturnsFalse_WhenNoNameserverLine()
    {
        string[] lines =
        [
            "# no resolver configured",
            "search example.org",
            "options edns0",
        ];

        var found = DnsSrvQuery.TryParseResolvConf(lines, out var resolver);

        Assert.False(found);
        Assert.Null(resolver);
    }

    [Fact]
    public void TryParseResolvConf_ReturnsFalse_WhenEmpty()
    {
        var found = DnsSrvQuery.TryParseResolvConf([], out var resolver);

        Assert.False(found);
        Assert.Null(resolver);
    }
}
